<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class GovernmentPortalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        // Disable foreign key checks to allow truncation
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('projects')->truncate();
        DB::table('posts')->truncate();
        DB::table('tenders')->truncate();
        DB::table('vacancies')->truncate();
        DB::table('woredas')->truncate();
        DB::table('tourist_sites')->truncate();
        DB::table('hero_slides')->truncate();

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // 1. Projects (projects table)
        DB::table('projects')->insert([
            [
                'title_en' => 'Kemise City Clean Water Expansion',
                'title_am' => 'የከሚሴ ከተማ ንፁህ መጠጥ ውሃ ማስፋፊያ',
                'title_or' => 'Baballina Bishaan Dhugaatii Qulqulluu Magaalaa Kamisee',
                'description_en' => 'Expanding the clean water supply network to reach newly developed residential areas in Kemise.',
                'description_am' => 'በከሚሴ ከተማ አዲስ ለተገነቡ የመኖሪያ አካባቢዎች የንፁህ መጠጥ ውሃ መስመር ዝርጋታ።',
                'description_or' => 'Sarara bishaan dhugaatii qulqulluu gara naannoo jireenyaa haaraa magaalaa Kamiseetti baballisuu.',
                'location_en' => 'Kemise City',
                'start_date' => '2025-09-01',
                'end_date' => '2026-08-30',
                'status' => 'Ongoing',
                'budget' => 45000000.00,
                'progress' => 65,
                'contractor' => 'Amhara Water Works Construction',
                'funding_source' => 'Regional Budget',
                'cover_image_url' => '/storage/projects/kemise_water.jpg',
            ],
            [
                'title_en' => 'Dawa Chefa Agricultural Tech Hub',
                'title_am' => 'የዳዋ ጨፋ የግብርና ቴክኖሎጂ ማዕከል',
                'title_or' => 'Wiirtuu Teeknooloojii Qonnaa Dawaa Caffee',
                'description_en' => 'An AI-powered integrated platform and physical training center for local farmers to improve crop yields.',
                'description_am' => 'የአካባቢው አርሶ አደሮች ምርታማነትን እንዲያሳድጉ የሚያግዝ በሰው ሰራሽ አስተውሎት የተደገፈ የግብርና ማዕከል።',
                'description_or' => 'Wiirtuu leenjii fi pilaatfoormii teeknooloojiin deeggarame kan horsiisee bultoota naannichaatiif oomishaa fi oomishtummaa guddisu.',
                'location_en' => 'Dawa Chefa',
                'start_date' => '2026-01-15',
                'end_date' => '2026-12-30',
                'status' => 'Planning',
                'budget' => 12000000.00,
                'progress' => 10,
                'contractor' => 'AgriTech Solutions PLC',
                'funding_source' => 'Federal Grant & NGO',
                'cover_image_url' => '/storage/projects/dawa_agritech.jpg',
            ],
            [
                'title_en' => 'Bati-Mille Road Asphalt Upgrading',
                'title_am' => 'የባቲ-ሚሌ መንገድ አስፋልት ማሻሻያ',
                'title_or' => 'Fooyya\'iinsa Daandii Asfaaltii Baatii-Millee',
                'description_en' => 'Upgrading the gravel road to standard asphalt to facilitate regional trade and transport.',
                'description_am' => 'የክልሉን የንግድና የትራንስፖርት እንቅስቃሴ ለማሳለጥ የጠጠር መንገዱን ወደ ደረጃውን የጠበቀ አስፋልት ማሳደግ።',
                'description_or' => 'Sochii daldalaa fi geejjibaa naannichaa saffisiisuuf daandii cirrachaa gara asfaaltiitti sadarkaa isaa eeggateen fooyyessuu.',
                'location_en' => 'Bati to Mille Route',
                'start_date' => '2024-05-10',
                'end_date' => '2025-11-20',
                'status' => 'Completed',
                'budget' => 250000000.00,
                'progress' => 100,
                'contractor' => 'Ethiopian Roads Administration',
                'funding_source' => 'Federal Budget',
                'cover_image_url' => '/storage/projects/bati_road.jpg',
            ],
            [
                'title_en' => 'Zone E-Governance Infrastructure',
                'title_am' => 'የዞኑ የኤሌክትሮኒክስ አስተዳደር መሠረተ ልማት',
                'title_or' => 'Bu\'uura Misoomaa Bulchiinsa Elektirooniksii Godinichaa',
                'description_en' => 'Deployment of a comprehensive multi-layered system architecture for a one-stop municipal service center.',
                'description_am' => 'ለአንድ ማዕከል የማዘጋጃ ቤት አገልግሎት አሰጣጥ የተሟላ የሲስተም አርክቴክቸር ዝርጋታ።',
                'description_or' => 'Tajaajila qopheessaa wiirtuu tokkoo kennuuf ijaarsa sirna teeknooloojii guutuu ta\'e diriirsuu.',
                'location_en' => 'Kemise (Zone HQ)',
                'start_date' => '2026-02-01',
                'end_date' => '2026-10-01',
                'status' => 'Ongoing',
                'budget' => 8500000.00,
                'progress' => 35,
                'contractor' => 'OSZA IT Department',
                'funding_source' => 'Zone Administration',
                'cover_image_url' => '/storage/projects/egov_infrastructure.jpg',
            ],
            [
                'title_en' => 'Artuma Fursi General Hospital Construction',
                'title_am' => 'የአርጡማ ፉርሲ አጠቃላይ ሆስፒታል ግንባታ',
                'title_or' => 'Ijaarsa Hospitaala Waliigalaa Arxuumaa Fursii',
                'description_en' => 'Construction of a new general hospital equipped with modern medical facilities to serve the local population.',
                'description_am' => 'ለአካባቢው ህብረተሰብ አገልግሎት የሚሰጥ በዘመናዊ የህክምና መሳሪያዎች የተሟላ አዲስ አጠቃላይ ሆስፒታል ግንባታ።',
                'description_or' => 'Ijaarsa hospitaala waliigalaa haaraa meeshaalee yaalaa ammayyaatiin guutamee hawaasa naannichaatiif tajaajilu.',
                'location_en' => 'Artuma Fursi',
                'start_date' => '2025-01-10',
                'end_date' => '2027-06-30',
                'status' => 'Ongoing',
                'budget' => 150000000.00,
                'progress' => 45,
                'contractor' => 'National Health Construction PLC',
                'funding_source' => 'Ministry of Health',
                'cover_image_url' => '/storage/projects/artuma_hospital.jpg',
            ],
        ]);

        // 2. News/Articles (posts table)
        DB::table('posts')->insert([
            [
                'title_en' => 'Official Launch of the OSZA Digital Portal',
                'title_am' => 'የኦሮሞ ብሔረሰብ አስተዳደር ዞን ዲጂታል ፖርታል ይፋዊ ማስጀመሪያ',
                'title_or' => 'Eebbifama Poortaalii Dijitaalaa Godina Addaa Oromoo',
                'content_en' => 'The Oromo Special Zone administration has officially launched its new comprehensive, multilingual digital portal to enhance public service delivery and government transparency.',
                'content_am' => 'የኦሮሞ ብሔረሰብ አስተዳደር ዞን የመንግስት አገልግሎት አሰጣጥን እና ግልፅነትን ለማሻሻል አዲሱን የተሟላ እና ባለብዙ ቋንቋ ዲጂታል ፖርታል በይፋ አስጀመረ።',
                'content_or' => 'Bulchiinsi Godina Addaa Oromoo kenniinsa tajaajila uummataa fi iftoomina mootummaa fooyyessuuf poortaalii dijitaalaa haaraa afaan baay\'een hojjetu ifatti eebbiseera.',
                'category' => 'news',
                'status' => 'published',
                'thumbnail_url' => '/storage/posts/portal_launch.jpg',
                'published_at' => $now->copy()->subDays(2),
                'created_at' => $now->copy()->subDays(2),
                'updated_at' => $now->copy()->subDays(2),
            ],
            [
                'title_en' => 'Annual Bati Cultural Festival Dates Announced',
                'title_am' => 'ዓመታዊው የባቲ የባህል ፌስቲቫል ቀናት ታወቁ',
                'title_or' => 'Guyyootni Ayyaana Aadaa Baatii Waggaa Ibsaman',
                'content_en' => 'The annual Bati Cultural Festival, celebrating the rich heritage and historical trade routes of the zone, will take place next month. Visitors from all regions are welcome.',
                'content_am' => 'የዞኑን የበለፀገ ታሪክ እና የንግድ መስመር የሚያከብረው ዓመታዊው የባቲ የባህል ፌስቲቫል በሚቀጥለው ወር ይካሄዳል። ከሁሉም ክልሎች የሚመጡ ጎብኚዎች ተጋብዘዋል።',
                'content_or' => 'Ayyaanni aadaa Baatii waggaa, seenaa fi sarara daldalaa godinichaa beeksisu, ji\'a dhufu ni kabajama. Daawwattoonni naannolee hunda irraa dhufan ni simatamu.',
                'category' => 'update',
                'status' => 'published',
                'thumbnail_url' => '/storage/posts/bati_festival.jpg',
                'published_at' => $now->copy()->subDays(5),
                'created_at' => $now->copy()->subDays(5),
                'updated_at' => $now->copy()->subDays(5),
            ],
            [
                'title_en' => 'New Agricultural Guidelines Released for Farmers',
                'title_am' => 'አዲስ የግብርና መመሪያ ለአርሶ አደሮች ወጣ',
                'title_or' => 'Qajeelfamni Qonnaa Haaraan Qotee Bultootaaf Bahe',
                'content_en' => 'The Zone Agricultural Bureau has released updated guidelines focusing on climate-resilient crop varieties and modern irrigation techniques for the upcoming season.',
                'content_am' => 'የዞኑ ግብርና ቢሮ የአየር ንብረት ለውጥን መቋቋም በሚችሉ የሰብል ዝርያዎች እና ዘመናዊ የመስኖ ዘዴዎች ላይ ያተኮረ የተሻሻለ መመሪያ ለመጪው የምርት ዘመን አውጥቷል።',
                'content_or' => 'Biiroon Qonnaa Godinichaa qajeelfama haaraa sanyii midhaanii jijjiirama haala qilleensaa dandamachuu danda\'anii fi mala jallisii ammayyaa irratti xiyyeeffatu baaseera.',
                'category' => 'news',
                'status' => 'published',
                'thumbnail_url' => '/storage/posts/agriculture_guide.jpg',
                'published_at' => $now->copy()->subDays(10),
                'created_at' => $now->copy()->subDays(10),
                'updated_at' => $now->copy()->subDays(10),
            ],
            [
                'title_en' => 'Youth Entrepreneurship Training Completed',
                'title_am' => 'የወጣቶች ስራ ፈጠራ ስልጠና ተጠናቀቀ',
                'title_or' => 'Leenjiin Uumuu Hojii Dargaggootaa Xumurame',
                'content_en' => 'Over 500 youths from Jile Timuga and Senbete woredas have successfully completed a three-week training program on digital entrepreneurship and business management.',
                'content_am' => 'ከጅሌ ጥሙጋ እና ሰንበቴ ወረዳዎች የተውጣጡ ከ500 በላይ ወጣቶች በዲጂታል ስራ ፈጠራ እና ቢዝነስ አስተዳደር ላይ የተሰጠውን የሶስት ሳምንት ስልጠና በስኬት አጠናቀቁ።',
                'content_or' => 'Dargaggoonni 500 ol aanaalee Jillee Dhummuugaa fi Sanbateerraa walitti babba\'an leenjii torbee sadiif uumuu hojii dijitaalaa fi bulchiinsa daldalaa irratti kenname milkiin xumuraniiru.',
                'category' => 'news',
                'status' => 'published',
                'thumbnail_url' => '/storage/posts/youth_training.jpg',
                'published_at' => $now->copy()->subDays(15),
                'created_at' => $now->copy()->subDays(15),
                'updated_at' => $now->copy()->subDays(15),
            ],
            [
                'title_en' => 'Notice: Scheduled System Maintenance',
                'title_am' => 'ማስታወቂያ፡ የታቀደ የሲስተም ጥገና',
                'title_or' => 'Beeksisa: Suphaa Sirnaa Sagantaame',
                'content_en' => 'The zone\'s internal government network will undergo scheduled maintenance this weekend. Some municipal online services may experience temporary downtime.',
                'content_am' => 'የዞኑ የውስጥ የመንግስት ኔትወርክ በዚህ ቅዳሜና እሁድ የታቀደ ጥገና ይደረግለታል። አንዳንድ የማዘጋጃ ቤት የመስመር ላይ አገልግሎቶች ለጊዜው ሊቋረጡ ይችላሉ።',
                'content_or' => 'Neetworkiin keessoo mootummaa godinichaa dhuma torbee kanaa suphaan ni taasifamaaf. Tajaajiloonni qopheessaa toora intarneetii tokko tokko yeroof addaan cituu danda\'u.',
                'category' => 'news',
                'status' => 'draft',
                'thumbnail_url' => '/storage/posts/maintenance.jpg',
                'published_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // 3. Tenders (tenders table)
        DB::table('tenders')->insert([
            [
                'title_en' => 'Procurement of IT Equipment and Servers',
                'title_am' => 'የአይቲ ዕቃዎች እና ሰርቨሮች ግዢ',
                'title_or' => 'Bittaa Meeshaalee IT fi Sarvarii',
                'description_en' => 'Supply and installation of enterprise-grade servers and networking equipment for the new Zone Data Center.',
                'description_am' => 'ለአዲሱ የዞኑ ዳታ ማዕከል የሰርቨሮች እና የኔትወርክ ዕቃዎች አቅርቦት እና ገጠማ።',
                'description_or' => 'Dhiyeessii fi dhaabbii sarvarootaa fi meeshaalee neetworkii Wiirtuu Daataa Godinaa haaraaf.',
                'ref_number' => 'OSZA-IT-2026-001',
                'deadline' => '2026-04-15 14:00:00',
                'status' => 'active',
            ],
            [
                'title_en' => 'Construction of Public Library in Dawa Chefa',
                'title_am' => 'በዳዋ ጨፋ የህዝብ ቤተ-መጻሕፍት ግንባታ',
                'title_or' => 'Ijaarsa Mana Kitaabaa Uummataa Dawaa Caffeetti',
                'description_en' => 'General contracting services for the construction of a G+2 public library and study center.',
                'description_am' => 'ባለ 2 ፎቅ የህዝብ ቤተ-መጻሕፍት እና የማጥኛ ማዕከል ግንባታ።',
                'description_or' => 'Tajaajila ijaarsa mana kitaabaa uummataa fi wiirtuu qo\'annoo darbii 2 qabu.',
                'ref_number' => 'OSZA-EDU-2026-042',
                'deadline' => '2026-05-01 10:00:00',
                'status' => 'active',
            ],
            [
                'title_en' => 'Supply of Agricultural Fertilizers',
                'title_am' => 'የግብርና ማዳበሪያ አቅርቦት',
                'title_or' => 'Dhiyeessii Xaa\'oo Qonnaa',
                'description_en' => 'Procurement of 50,000 quintals of Urea and NPS fertilizers for the upcoming Meher farming season.',
                'description_am' => 'ለመጪው የመኸር እርሻ ዘመን የሚሆን 50,000 ኩንታል ዩሪያ እና ኤን.ፒ.ኤስ ማዳበሪያ ግዢ።',
                'description_or' => 'Bittaa xaa\'oo Yuuriyaa fi NPS kuntaala 50,000 yeroo qonna arfaasaa dhufuuf.',
                'ref_number' => 'OSZA-AGR-2026-011',
                'deadline' => '2026-03-20 12:00:00',
                'status' => 'closed',
            ],
            [
                'title_en' => 'Vehicle Maintenance and Spare Parts',
                'title_am' => 'የተሽከርካሪ ጥገና እና የመለዋወጫ ዕቃዎች',
                'title_or' => 'Suphaa Konkolaataa fi Meeshaalee Jijjiiramaa',
                'description_en' => 'Annual framework contract for the maintenance of zone administration vehicles (Toyota Hilux and Land Cruisers).',
                'description_am' => 'የዞኑ አስተዳደር ተሽከርካሪዎችን (ቶዮታ ሃይለክስ እና ላንድ ክሩዘር) ዓመታዊ የጥገና ውል።',
                'description_or' => 'Waliigaltee suphaa konkolaattota bulchiinsa godinichaa (Toyota Hilux fi Land Cruiser) waggaa.',
                'ref_number' => 'OSZA-TRANS-2026-005',
                'deadline' => '2026-02-28 17:00:00',
                'status' => 'archived',
            ],
            [
                'title_en' => 'Solar Panel Installation for Rural Clinics',
                'title_am' => 'ለገጠር ክሊኒኮች የሶላር ፓኔል ገጠማ',
                'title_or' => 'Kilinikoota Baadiyaaf Dhaabbii Solaarii',
                'description_en' => 'Supply, installation, and commissioning of solar power systems for 15 off-grid rural health posts.',
                'description_am' => 'ከኤሌክትሪክ መስመር ርቀው ለሚገኙ 15 የገጠር ጤና ኬላዎች የሶላር ኃይል አቅርቦት እና ገጠማ።',
                'description_or' => 'Kilinikoota baadiyaa sarara ibsaa irraa fagaatanii argaman 15f dhiyeessii fi dhaabbii humna adu.',
                'ref_number' => 'OSZA-HLT-2026-019',
                'deadline' => '2026-04-30 14:00:00',
                'status' => 'active',
            ],
        ]);

        // 4. Vacancies (vacancies table)
        DB::table('vacancies')->insert([
            [
                'title_en' => 'Senior Software Developer',
                'title_am' => 'ከፍተኛ የሶፍትዌር አልሚ',
                'title_or' => 'Ogeessa Sooftiweerii Olaanaa',
                'description_en' => 'Seeking an experienced developer to manage the architecture of the zone\'s e-government portal.',
                'description_am' => 'የዞኑን የኤሌክትሮኒክስ አስተዳደር ፖርታል የሚያስተዳድር ልምድ ያለው አልሚ እንፈልጋለን።',
                'description_or' => 'Ogeessa muuxannoo qabu kan poortaalii bulchiinsa elektirooniksii godinichaa bulchu barbaadna.',
                'requirements_en' => 'BSc in Computer Science, 5+ years experience with PHP/Laravel and React.',
                'requirements_am' => 'በኮምፒውተር ሳይንስ የመጀመሪያ ዲግሪ፣ በ PHP/Laravel እና React ከ5 ዓመት በላይ የስራ ልምድ።',
                'requirements_or' => 'Digrii jalqabaa Saayinsii Kompiwtaraatiin, muuxannoo waggaa 5 ol PHP/Laravel fi React irratti qabu.',
                'department' => 'Information Technology',
                'vacancy_type' => 'Full-time',
                'location_en' => 'Kemise HQ',
                'deadline' => '2026-04-10',
                'is_active' => true,
            ],
            [
                'title_en' => 'Agricultural Extension Expert',
                'title_am' => 'የግብርና ኤክስቴንሽን ባለሙያ',
                'title_or' => 'Ogeessa Ekisteenshinii Qonnaa',
                'description_en' => 'Provide technical support and training to farmers on modern agricultural practices.',
                'description_am' => 'ለአርሶ አደሮች በዘመናዊ የግብርና አሰራሮች ላይ ቴክኒካዊ ድጋፍ እና ስልጠና መስጠት።',
                'description_or' => 'Qotee bultootaaf hojimaata qonnaa ammayyaa irratti deeggarsa teeknikaa fi leenjii kennuu.',
                'requirements_en' => 'BSc in Agriculture or Agronomy, excellent communication skills in Amharic and Afaan Oromoo.',
                'requirements_am' => 'በግብርና የመጀመሪያ ዲግሪ፣ በአማርኛ እና አፋን ኦሮሞ ጥሩ የመግባባት ችሎታ።',
                'requirements_or' => 'Digrii jalqabaa Qonnaan, dandeettii quunnamtii gaarii Afaan Amaaraa fi Afaan Oromootiin qabu.',
                'department' => 'Agricultural Bureau',
                'vacancy_type' => 'Contract',
                'location_en' => 'Artuma Fursi',
                'deadline' => '2026-04-05',
                'is_active' => true,
            ],
            [
                'title_en' => 'Civil Engineer',
                'title_am' => 'የሲቪል መሃንዲስ',
                'title_or' => 'Injinara Siivilii',
                'description_en' => 'Supervise and evaluate ongoing infrastructure and road projects within the zone.',
                'description_am' => 'በዞኑ ውስጥ በመካሄድ ላይ ያሉ የመሠረተ ልማት እና የመንገድ ፕሮጀክቶችን መቆጣጠር እና መገምገም::',
                'description_or' => 'Pirojektoota bu\'uura misoomaa fi daandii godinicha keessatti hojjetamaa jiran to\'achuu fi gamaaggamuu.',
                'requirements_en' => 'BSc in Civil Engineering, valid professional license, 3+ years experience.',
                'requirements_am' => 'በሲቪል ምህንድስና የመጀመሪያ ዲግሪ፣ የታደሰ የሙያ ፈቃድ፣ ከ3 ዓመት በላይ የስራ ልምድ።',
                'requirements_or' => 'Digrii jalqabaa Injinariingii Siiviliitiin, eeyyama ogummaa haaromfame, muuxannoo waggaa 3 ol.',
                'department' => 'Infrastructure & Development',
                'vacancy_type' => 'Full-time',
                'location_en' => 'Bati',
                'deadline' => '2026-04-20',
                'is_active' => true,
            ],
            [
                'title_en' => 'Public Relations Officer',
                'title_am' => 'የህዝብ ግንኙነት ኦፊሰር',
                'title_or' => 'Ogeessa Quunnamtii Uummataa',
                'description_en' => 'Manage communications, press releases, and social media presence for the Zone Administration.',
                'description_am' => 'ለዞኑ አስተዳደር መግለጫዎችን እና የማህበራዊ ሚዲያ ስራዎችን ማስተዳደር::',
                'description_or' => 'Ibsa miidiyaa fi hojiiwwan miidiyaa hawaasaa Bulchiinsa Godinichaa gaggeessuu.',
                'requirements_en' => 'BA in Journalism or PR, fluency in English, Amharic, and Afaan Oromoo.',
                'requirements_am' => 'በጋዜጠኝነት ወይም ህዝብ ግንኙነት የመጀመሪያ ዲግሪ፣ እንግሊዝኛ፣ አማርኛ እና አፋን ኦሮሞ አቀላጥፎ የሚናገር።',
                'requirements_or' => 'Digrii jalqabaa Gaazexeessummaa ykn Quunnamtii Uummataatiin, Afaan Ingiliizii, Amaaraa fi Oromoo raawwatee kan dubbatu.',
                'department' => 'Mayor\'s Office',
                'vacancy_type' => 'Full-time',
                'location_en' => 'Kemise HQ',
                'deadline' => '2026-03-30',
                'is_active' => true,
            ],
            [
                'title_en' => 'Data Encoder',
                'title_am' => 'ዳታ ኢንኮደር',
                'title_or' => 'Galchaa Daataa',
                'description_en' => 'Digitize paper records and input census data into the new management system.',
                'description_am' => 'በወረቀት ላይ ያሉ መረጃዎችን ወደ አዲሱ አስተዳደር ሲስተም ማስገባት::',
                'description_or' => 'Ragaalee waraqaa irra jiran gara sirna bulchiinsa haaraatti galchuu.',
                'requirements_en' => 'Diploma in IT or related field, typing speed of 40+ WPM.',
                'requirements_am' => 'በአይቲ ዲፕሎማ፣ በደቂቃ ከ40 ቃላት በላይ የመተየብ ፍጥነት::',
                'requirements_or' => 'Diploomaa IT ykn damee walqabatuun, saffisa barreessuu daqiiqaatti jechoota 40 ol.',
                'department' => 'Statistics Bureau',
                'vacancy_type' => 'Contract',
                'location_en' => 'Jile Timuga',
                'deadline' => '2026-04-12',
                'is_active' => true,
            ],
        ]);

        // 5. Woredas (woredas table)
        DB::table('woredas')->insert([
            [
                'name_en' => 'Kemise City Administration',
                'name_am' => 'ከሚሴ ከተማ አስተዳደር',
                'name_or' => 'Bulchiinsa Magaalaa Kamisee',
                'slug' => 'kemise-city',
                'description_en' => 'The capital and administrative center of the Oromo Special Zone.',
                'description_am' => 'የኦሮሞ ብሔረሰብ አስተዳደር ዞን ዋና ከተማ እና የአስተዳደር ማዕከል።',
                'description_or' => 'Magaalaa guddittii fi wiirtuu bulchiinsaa Godina Addaa Oromoo.',
                'population' => 120000,
                'area_km2' => 85.5,
                'capital_en' => 'Kemise',
                'capital_am' => 'ከሚሴ',
                'capital_or' => 'Kamisee',
                'administrator_name' => 'Ato Hussen Mohammed',
                'mission_en' => 'To provide efficient urban services and foster digital and economic growth.',
                'mission_am' => 'ቀልጣፋ የከተማ አገልግሎቶችን መስጠት እና የዲጂታል እና ኢኮኖሚያዊ ዕድገትን ማሳደግ::',
                'mission_or' => 'Tajaajila magaalaa si\'aawaa ta\'e kennuu fi guddina dijitaalaa fi dinagdee jajjabeessuu.',
                'vision_en' => 'To be a model smart city in the region by 2030.',
                'vision_am' => 'በ2030 በክልሉ ውስጥ ሞዴል ስማርት ከተማ መሆን::',
                'vision_or' => 'Bara 2030tti naannicha keessatti magaalaa ismaartii fakkeenya taatugahchuu.',
            ],
            [
                'name_en' => 'Bati',
                'name_am' => 'ባቲ',
                'name_or' => 'Baatii',
                'slug' => 'bati',
                'description_en' => 'Famous for its historical significance and the largest open-air camel and livestock market in the region.',
                'description_am' => 'በታሪካዊ ፋይዳዋ እና በክልሉ ትልቁ የገበያ ስፍራ (የግመል እና የከብት ገበያ) የምትታወቅ::',
                'description_or' => 'Seenaa ishee fi gabaa gaalaa fi loonii guddichaan kan beekamtu.',
                'population' => 150000,
                'area_km2' => 1200.0,
                'capital_en' => 'Bati Town',
                'capital_am' => 'ባቲ ከተማ',
                'capital_or' => 'Magaalaa Baatii',
                'administrator_name' => 'W/ro Amina Ali',
                'mission_en' => 'To expand trade infrastructure and protect cultural heritage.',
                'mission_am' => 'የንግድ መሠረተ ልማትን ማስፋፋት እና የባህል ቅርሶችን መጠበቅ::',
                'mission_or' => 'Bu\'uura misoomaa daldalaa baballisuu fi hambaa aadaa eeguu.',
                'vision_en' => 'To become the leading commercial and cultural tourism hub.',
                'vision_am' => 'ቀዳሚ የንግድ እና የባህል ቱሪዝም ማዕከል መሆን::',
                'vision_or' => 'Wiirtuu daldalaa fi turizimii aadaa adda duree ta\'uu.',
            ],
            [
                'name_en' => 'Dawa Chefa',
                'name_am' => 'ዳዋ ጨፋ',
                'name_or' => 'Dawaa Caffee',
                'slug' => 'dawa-chefa',
                'description_en' => 'Known for the Chefa Valley, highly fertile land crucial for agriculture and livestock grazing.',
                'description_am' => 'ለግብርና እና ለከብት ግጦሽ እጅግ ጠቃሚ በሆነው የጨፋ ሸለቆ የምትታወቅ::',
                'description_or' => 'Sulula Caffee, lafa qonnaa fi dheedicha looniif baay\'ee mijaawaa ta\'een kan beekamtu.',
                'population' => 180000,
                'area_km2' => 950.2,
                'capital_en' => 'Kemise (Shared)',
                'capital_am' => 'ከሚሴ',
                'capital_or' => 'Kamisee',
                'administrator_name' => 'Ato Kemal Ahmed',
                'mission_en' => 'To modernize agriculture and ensure food security.',
                'mission_am' => 'ግብርናን ማዘመን እና የምግብ ዋስትናን ማረጋገጥ::',
                'mission_or' => 'Qonna ammayyeessuu fi wabii midhaan nyaataa mirkaneessuu.',
                'vision_en' => 'An agricultural powerhouse driven by modern technology.',
                'vision_am' => 'በዘመናዊ ቴክኖሎጂ የተደገፈ የግብርና ሃይል መሆን::',
                'vision_or' => 'Humni qonnaa teeknooloojii ammayyaatiin oofamu ta\'uu.',
            ],
            [
                'name_en' => 'Artuma Fursi',
                'name_am' => 'አርጡማ ፉርሲ',
                'name_or' => 'Arxuumaa Fursii',
                'slug' => 'artuma-fursi',
                'description_en' => 'A diverse woreda focusing on both agriculture and emerging rural industries.',
                'description_am' => 'በግብርና እና በማደግ ላይ ባሉ የገጠር ኢንዱስትሪዎች ላይ ያተኮረ ወረዳ::',
                'description_or' => 'Aanaa qonnaa fi industiriiwwan baadiyaa guddachaa jiran irratti xiyyeeffatu.',
                'population' => 110000,
                'area_km2' => 820.5,
                'capital_en' => 'Chefa Robit',
                'capital_am' => 'ጨፋ ሮቢት',
                'capital_or' => 'Caffee Roobiit',
                'administrator_name' => 'Ato Seid Ibrahim',
                'mission_en' => 'Enhancing rural infrastructure and access to health services.',
                'mission_am' => 'የገጠር መሠረተ ልማትን እና የጤና አገልግሎት ተደራሽነትን ማሳደግ::',
                'mission_or' => 'Bu\'uura misoomaa baadiyaa fi tajaajila fayyaa baballisuu.',
                'vision_en' => 'A prosperous community with standard social amenities.',
                'vision_am' => 'ደረጃውን የጠበቀ ማህበራዊ አገልግሎት ያለው የበለፀገ ማህበረሰብ መፍጠር::',
                'vision_or' => 'Hawaasa badhaadhaa tajaajila hawaasummaa sadarkaa isaa eeggate qabu uumuu.',
            ],
            [
                'name_en' => 'Jile Timuga',
                'name_am' => 'ጅሌ ጥሙጋ',
                'name_or' => 'Jillee Dhummuugaa',
                'slug' => 'jile-timuga',
                'description_en' => 'Situated along major transport routes, important for regional connectivity and trade.',
                'description_am' => 'በዋና ዋና የትራንስፖርት መስመሮች ላይ የምትገኝ፣ ለክልላዊ ትስስር እና ንግድ አስፈላጊ የሆነች::',
                'description_or' => 'Sarara geejjibaa gurguddoo irratti kan argamtu, walitti hidhamiinsa naannoo fi daldalaaf murteessituu kan taate.',
                'population' => 95000,
                'area_km2' => 740.0,
                'capital_en' => 'Senbete',
                'capital_am' => 'ሰንበቴ',
                'capital_or' => 'Sanbate',
                'administrator_name' => 'Ato Tadesse Hassen',
                'mission_en' => 'To promote youth employment and safe transport networks.',
                'mission_am' => 'የወጣቶችን የስራ እድል እና ደህንነቱ የተጠበቀ የትራንስፖርት ትስስር ማሳደግ::',
                'mission_or' => 'Carraa hojii dargaggootaa fi neetworkii geejjibaa nageenyummaan isaa eeggame jajjabeessuu.',
                'vision_en' => 'A connected, youth-driven economic corridor.',
                'vision_am' => 'በወጣቶች የሚመራ እና የተሳሰረ የኢኮኖሚ ኮሪደር መፍጠር::',
                'vision_or' => 'Koriidarii dinagdee dargaggootaan durfamu uumuu.',
            ],
        ]);

        // 6. Tourism (tourist_sites table)
        DB::table('tourist_sites')->insert([
            [
                'name_en' => 'Bati Livestock Market',
                'name_am' => 'የባቲ የከብት ገበያ',
                'name_or' => 'Gabaa Loonii Baatii',
                'slug' => 'bati-livestock-market',
                'description_en' => 'One of the largest open-air markets in Africa, famous for camels and traditional crafts. It is a historical meeting point for various ethnic groups.',
                'description_am' => 'በአፍሪካ ውስጥ ካሉ ትላልቅ ክፍት ገበያዎች አንዱ፣ በግመሎች እና በባህላዊ እደ ጥበባት ታዋቂ:: የተለያየ ብሔረሰቦች ታሪካዊ መገናኛ ስፍራ::',
                'description_or' => 'Gabaawwan banaa Afrikaa keessaa isa guddaa, gaalaa fi aadaa harkaan hojjetamuun kan beekamu. Bakka seena qabeessa saboota adda addaa walitti fidu.',
                'location_name_en' => 'Bati Woreda',
                'is_active' => true,
            ],
            [
                'name_en' => 'Chefa Wetland and Wildlife',
                'name_am' => 'የጨፋ ረግረግ እና የዱር እንስሳት',
                'name_or' => 'Caffee fi Bineensota Bosonaa',
                'slug' => 'chefa-wetland-and-wildlife',
                'description_en' => 'A vast wetland area serving as a sanctuary for migratory birds and extensive grazing land, offering excellent eco-tourism and bird-watching opportunities.',
                'description_am' => 'ለስደተኛ ወፎች እና ለሰፊ የግጦሽ መሬት መሸሸጊያ ሆኖ የሚያገለግል ሰፊ ረግረግ፣ ለኢኮ-ቱሪዝም እና ወፎችን ለመመልከት ምቹ ስፍራ::',
                'description_or' => 'Lafoota jiidhaa bal\'aa simbirroota godaananiif dawoo fi lafa dheedumsaa ta\'e, carraa ikoo-turizimii fi simbirroota daawwachuuf mijaawaa ta\'e.',
                'location_name_en' => 'Dawa Chefa',
                'is_active' => true,
            ],
            [
                'name_en' => 'Senbete Cultural Market',
                'name_am' => 'የሰንበቴ ባህላዊ ገበያ',
                'name_or' => 'Gabaa Aadaa Sanbate',
                'slug' => 'senbete-cultural-market',
                'description_en' => 'A vibrant weekly market showcasing regional agricultural products, traditional clothing, and a crossroads of diverse cultures.',
                'description_am' => 'የአካባቢውን የግብርና ምርቶች፣ ባህላዊ አልባሳት እና የተለያዩ ባህሎች መገናኛ የሚያሳይ ሳምንታዊ ገበያ::',
                'description_or' => 'Gabaa torbee oomishaa qonnaa naannichaa, uffata aadaa fi walqaxxaamura aadaa adda addaa agarsiisu.',
                'location_name_en' => 'Jile Timuga (Senbete Town)',
                'is_active' => true,
            ],
            [
                'name_en' => 'Kemise Grand Mosque and Islamic Center',
                'name_am' => 'የከሚሴ ታላቁ መስጊድ እና የእስልምና ማዕከል',
                'name_or' => 'Masgiida Guddaa Kamisee fi Wiirtuu Islaamummaa',
                'slug' => 'kemise-grand-mosque-and-islamic-center',
                'description_en' => 'A beautifully architected mosque serving as the spiritual heart of the city and a center for Islamic learning in the zone.',
                'description_am' => 'የከተማዋ መንፈሳዊ ማዕከል እና የዞኑ የእስልምና ትምህርት ማዕከል ሆኖ የሚያገለግል ውብ የስነ-ህንፃ ጥበብ ያለው መስጊድ::',
                'description_or' => 'Masgiida ijaarsa bareedaa qabu kan wiirtuu hafuuraa magaalaa fi wiirtuu barnoota amantii Islaamaa godinichaa ta\'e.',
                'location_name_en' => 'Kemise City Center',
                'is_active' => true,
            ],
            [
                'name_en' => 'Borkena River Valley Landscapes',
                'name_am' => 'የቦርከና ወንዝ ሸለቆ ገጽታዎች',
                'name_or' => 'Mulkii Sulula Laga Boorkanaa',
                'slug' => 'borkena-river-valley-landscapes',
                'description_en' => 'Scenic river valleys offering beautiful landscapes for hiking, photography, and exploring traditional farming communities along the riverbanks.',
                'description_am' => 'ለእግር ጉዞ፣ ለፎቶግራፍ እና በወንዙ ዳርቻ ያሉ ባህላዊ የግብርና ማህበረሰቦችን ለማሰስ የሚያማምሩ ገጽታዎችን የሚያቀርቡ የሸለቆ አካባቢዎች::',
                'description_or' => 'Sululoota lagaa mulkii bareedaa qaban kan miilaan deemuuf, suuraa kaasuu fi hawaasa qonnaa aadaa qarqara lagaatti argaman daawwachuuf mijaawaa ta\'an.',
                'location_name_en' => 'Borders of Kemise and Dawa Chefa',
                'is_active' => true,
            ],
        ]);

        // 7. Hero Slides
        DB::table('hero_slides')->insert([
            [
                'title_en' => 'Welcome to Oromo Special Zone',
                'title_am' => 'እንኳን ወደ ኦሮሞ ብሔረሰብ አስተዳደር ዞን በደህና መጡ',
                'title_or' => 'Baga Gara Godina Addaa Oromoo Nagaan Dhuftan',
                'subtitle_en' => 'Discover the rich history, diverse culture, and rapid development of our growing region.',
                'subtitle_am' => 'የዞናችንን የበለፀገ ታሪክ፣ የተለያዩ ባህሎች እና ፈጣን እድገት ያግኙ።',
                'subtitle_or' => 'Seenaa badhaadhaa, aadaa adda addaa fi guddina saffisaa naannoo keenyaa daawwadhaa.',
                'media_url' => '/storage/hero/slide_1.jpg',
                'media_type' => 'image',
                'cta_text' => 'Read More',
                'cta_text_am' => 'ተጨማሪ ያንብቡ',
                'cta_text_or' => 'Dabalata Dubbisi',
                'page' => 'home',
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title_en' => 'Cultivating Sustainable Growth',
                'title_am' => 'ዘላቂ የኢኮኖሚ እና የግብርና ልማት',
                'title_or' => 'Guddina Itti Fufiinsa Qabu Fiduu',
                'subtitle_en' => 'Investing in modern agriculture and infrastructure to build a prosperous future for all residents.',
                'subtitle_am' => 'ለሁሉም ነዋሪዎች የበለፀገ የወደፊት ጊዜን ለመገንባት በዘመናዊ ግብርና እና መሠረተ ልማት ላይ ኢንቨስት ማድረግ።',
                'subtitle_or' => 'Jiraattota hundaaf egeree badhaadhaa ijaaruuf qonna ammayyaa fi bu\'uura misoomaa irratti invast gochuu.',
                'media_url' => '/storage/hero/slide_2.jpg',
                'media_type' => 'image',
                'cta_text' => 'Our Projects',
                'cta_text_am' => 'ፕሮጀክቶቻችን',
                'cta_text_or' => 'Pirojektoota Keenya',
                'page' => 'home',
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title_en' => 'Experience Our Heritage',
                'title_am' => 'ቅርሳችንን ይጎብኙ',
                'title_or' => 'Hambaalee Keenya Daawwadhaa',
                'subtitle_en' => 'From the historic Bati market to breathtaking landscapes, explore the tourism heart of the region.',
                'subtitle_am' => 'ከታሪካዊው የባቲ ገበያ እስከ አስደናቂ የተፈጥሮ ገጽታዎች፣ የክልሉን የቱሪዝም ማዕከል ያስሱ።',
                'subtitle_or' => 'Gabaa seena qabeessa Baatii irraa kaasee hanga uumama dinqisiisaatti, wiirtuu tuuriziimii naannichaa daawwadhaa.',
                'media_url' => '/storage/hero/slide_3.jpg',
                'media_type' => 'image',
                'cta_text' => 'Explore Tourism',
                'cta_text_am' => 'ቱሪዝምን ያስሱ',
                'cta_text_or' => 'Tuuriziimii Daawwadhaa',
                'page' => 'home',
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}